const crypto=require('crypto'); const nodemailer=require('nodemailer'); const pool=require('../config/postgres'); const RefreshToken=require('../models/mongodb/RefreshToken'); const {hashSenha,compararSenha}=require('../utils/password'); const {criarAccessToken}=require('../utils/jwt');
const refreshDays=()=>Number(process.env.REFRESH_TOKEN_EXPIRES_DAYS||7);
function gerarRefresh(){return crypto.randomBytes(48).toString('hex');}
async function salvarRefresh(usuarioId,token){const expires=new Date(Date.now()+refreshDays()*86400000);await RefreshToken.create({tokenHash:crypto.createHash('sha256').update(token).digest('hex'),usuarioId,expiresAt:expires});}
async function registrar(req,res){try{let {nome,email,senha,perfil,area_id,setor_id,funcao_id}=req.body; email=String(email||'').trim().toLowerCase(); if(!nome||!email||!senha)return res.status(400).json({mensagem:'Nome, e-mail e senha são obrigatórios.'}); if(senha.length<8)return res.status(400).json({mensagem:'A senha deve possuir pelo menos 8 caracteres.'}); const exists=await pool.query('SELECT id FROM usuarios WHERE email=$1',[email]); if(exists.rowCount)return res.status(409).json({mensagem:'E-mail já cadastrado.'}); const hash=await hashSenha(senha); const r=await pool.query(`INSERT INTO usuarios(nome,email,senha_hash,perfil,area_id,setor_id,funcao_id) VALUES($1,$2,$3,'USUARIO',$4,$5,$6) RETURNING id,nome,email,perfil,area_id,setor_id,funcao_id,ativo`,[nome.trim(),email,hash,area_id||null,setor_id||null,funcao_id||null]); return res.status(201).json({mensagem:'Usuário cadastrado com sucesso.',usuario:r.rows[0]});}catch(e){console.error(e);return res.status(500).json({mensagem:'Erro ao cadastrar usuário.'});}}
async function login(req,res){try{const email=String(req.body.email||'').trim().toLowerCase(),senha=String(req.body.senha||'');const r=await pool.query(`SELECT * FROM usuarios WHERE email=$1`,[email]);if(!r.rowCount)return res.status(401).json({mensagem:'E-mail ou senha inválidos.'});const u=r.rows[0];if(!u.ativo)return res.status(403).json({mensagem:'Usuário bloqueado ou inativo.'});if(!(await compararSenha(senha,u.senha_hash)))return res.status(401).json({mensagem:'E-mail ou senha inválidos.'});const accessToken=criarAccessToken(u),refreshToken=gerarRefresh();await salvarRefresh(u.id,refreshToken);return res.json({mensagem:'Login realizado com sucesso.',token:accessToken,refreshToken,usuario:{id:u.id,nome:u.nome,email:u.email,perfil:u.perfil,area_id:u.area_id,setor_id:u.setor_id,funcao_id:u.funcao_id}});}catch(e){console.error(e);res.status(500).json({mensagem:'Erro ao realizar login.'});}}
async function refresh(req,res){try{const token=req.body.refreshToken;if(!token)return res.status(400).json({mensagem:'Refresh token obrigatório.'});const hash=crypto.createHash('sha256').update(token).digest('hex');const r=await RefreshToken.findOne({tokenHash:hash,revokedAt:null,expiresAt:{$gt:new Date()}});if(!r)return res.status(401).json({mensagem:'Refresh token inválido ou expirado.'});const u=(await pool.query('SELECT id,nome,email,perfil,area_id,setor_id,funcao_id,ativo FROM usuarios WHERE id=$1',[r.usuarioId])).rows[0];if(!u||!u.ativo)return res.status(401).json({mensagem:'Usuário inválido ou inativo.'});await RefreshToken.updateOne({_id:r._id},{$set:{revokedAt:new Date()}});const newRefresh=gerarRefresh();await salvarRefresh(u.id,newRefresh);res.json({token:criarAccessToken(u),refreshToken:newRefresh,usuario:u});}catch(e){console.error(e);res.status(500).json({mensagem:'Erro ao renovar sessão.'});}}
async function logout(req,res){try{if(req.body.refreshToken){const h=crypto.createHash('sha256').update(req.body.refreshToken).digest('hex');await RefreshToken.updateOne({tokenHash:h},{$set:{revokedAt:new Date()}});}res.json({mensagem:'Sessão encerrada.'});}catch(e){res.status(500).json({mensagem:'Erro ao encerrar sessão.'});}}
async function me(req,res){const r=await pool.query(`SELECT id,nome,email,perfil,area_id,setor_id,funcao_id,ativo,created_at FROM usuarios WHERE id=$1`,[req.usuario.id]);if(!r.rowCount)return res.status(404).json({mensagem:'Usuário não encontrado.'});res.json(r.rows[0]);}
async function forgotPassword(req,res){const email=String(req.body.email||'').trim().toLowerCase();const r=await pool.query('SELECT id,nome,email FROM usuarios WHERE email=$1 AND ativo=true',[email]);if(!r.rowCount)return res.json({mensagem:'Se o e-mail existir, as instruções serão enviadas.'});const raw=gerarRefresh(),hash=crypto.createHash('sha256').update(raw).digest('hex');await RefreshToken.create({tokenHash:`reset:${hash}`,usuarioId:r.rows[0].id,expiresAt:new Date(Date.now()+30*60000)});const url=`${process.env.FRONTEND_URL||'http://localhost:5173'}/reset-password?token=${raw}`;if(process.env.SMTP_HOST){const transporter=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:Number(process.env.SMTP_PORT||587)===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}});await transporter.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:email,subject:'Redefinição de senha',text:`Acesse: ${url}`});}res.json({mensagem:'Se o e-mail existir, as instruções serão enviadas.',devToken:process.env.NODE_ENV==='production'?undefined:raw});}
async function resetPassword(req,res){const {token,senha}=req.body;if(!token||!senha||senha.length<8)return res.status(400).json({mensagem:'Token e nova senha (mínimo 8 caracteres) são obrigatórios.'});const hash=crypto.createHash('sha256').update(token).digest('hex');const r=await RefreshToken.findOne({tokenHash:`reset:${hash}`,revokedAt:null,expiresAt:{$gt:new Date()}});if(!r)return res.status(400).json({mensagem:'Token inválido ou expirado.'});await pool.query('UPDATE usuarios SET senha_hash=$1,updated_at=NOW() WHERE id=$2',[await hashSenha(senha),r.usuarioId]);await RefreshToken.updateOne({_id:r._id},{$set:{revokedAt:new Date()}});res.json({mensagem:'Senha alterada com sucesso.'});}
module.exports={registrar,login,refresh,logout,me,forgotPassword,resetPassword};
