const pool=require('../config/postgres');
async function dashboard(req,res){let scope='';const p=[];if(req.usuario.perfil==='GESTOR'){p.push(req.usuario.area_id);scope=`AND t.area_id=$${p.length}`;}else if(req.usuario.perfil==='SUPERVISOR'){p.push(req.usuario.setor_id);scope=`AND t.setor_id=$${p.length}`;}else if(req.usuario.perfil==='USUARIO'){p.push(req.usuario.id,req.usuario.id);scope=`AND (t.responsavel_id=$${p.length-1} OR EXISTS(SELECT 1 FROM tarefa_usuarios tu WHERE tu.tarefa_id=t.id AND tu.usuario_id=$${p.length}))`;}
const q=await pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='PENDENTE')::int pendentes,COUNT(*) FILTER(WHERE status='EM_ANDAMENTO')::int em_andamento,COUNT(*) FILTER(WHERE status='CONCLUIDA')::int concluidas,COUNT(*) FILTER(WHERE status='CANCELADA')::int canceladas,COUNT(*) FILTER(WHERE prazo<NOW() AND status NOT IN('CONCLUIDA','CANCELADA'))::int atrasadas,COALESCE(ROUND(AVG(percentual_atendimento),2),0) percentual_medio,COALESCE(SUM(custo_estimado),0) custo_estimado,COALESCE(SUM(custo_real),0) custo_real FROM tarefas t WHERE t.ativo=true ${scope}`,p);
const [prioridades,areas,funcionarios]=await Promise.all([
 pool.query(`SELECT prioridade,COUNT(*)::int total FROM tarefas t WHERE t.ativo=true ${scope} GROUP BY prioridade ORDER BY prioridade`,p),
 pool.query(`SELECT a.nome,COUNT(t.id)::int total FROM tarefas t JOIN areas a ON a.id=t.area_id WHERE t.ativo=true ${scope} GROUP BY a.nome ORDER BY total DESC`,p),
 pool.query(`SELECT u.nome,COUNT(t.id)::int total FROM tarefas t JOIN usuarios u ON u.id=t.responsavel_id WHERE t.ativo=true ${scope} GROUP BY u.nome ORDER BY total DESC LIMIT 10`,p)
]);res.json({resumo:q.rows[0],por_prioridade:prioridades.rows,por_area:areas.rows,por_funcionario:funcionarios.rows});}
async function relatorio(req,res){let where=['t.ativo=true'],p=[];const add=(sql,v)=>{p.push(v);where.push(sql.replace('$N',`$${p.length}`));};if(req.query.funcionario_id)add('t.responsavel_id=$N',req.query.funcionario_id);if(req.query.area_id)add('t.area_id=$N',req.query.area_id);if(req.query.setor_id)add('t.setor_id=$N',req.query.setor_id);if(req.query.status)add('t.status=$N',req.query.status);if(req.query.prioridade)add('t.prioridade=$N',req.query.prioridade);if(req.query.data_inicio)add('t.created_at>=$N',req.query.data_inicio);if(req.query.data_fim)add("t.created_at<($N::date+INTERVAL '1 day')",req.query.data_fim);if(req.usuario.perfil==='GESTOR')add('t.area_id=$N',req.usuario.area_id);if(req.usuario.perfil==='SUPERVISOR')add('t.setor_id=$N',req.usuario.setor_id);if(req.usuario.perfil==='USUARIO')add('t.responsavel_id=$N',req.usuario.id);const r=await pool.query(`SELECT t.id,t.titulo,t.descricao,t.status,t.prioridade,t.percentual_atendimento,t.prazo,t.created_at,t.data_inicio,t.data_conclusao,t.custo_estimado,t.custo_real,u.nome responsavel,a.nome area,s.nome setor,f.nome funcao FROM tarefas t JOIN usuarios u ON u.id=t.responsavel_id JOIN areas a ON a.id=t.area_id LEFT JOIN setores s ON s.id=t.setor_id LEFT JOIN funcoes f ON f.id=u.funcao_id WHERE ${where.join(' AND ')} ORDER BY t.created_at DESC`,p);res.json(r.rows);}
module.exports={dashboard,relatorio};
